/** Small public-caption reader. No video download, API key, or dependency. */
const CLIENT_VERSION = "20.10.38";
const PLAYER_URL = "https://www.youtube.com/youtubei/v1/player?prettyPrint=false";
const VIDEO_ID = /^[A-Za-z0-9_-]{11}$/;

export interface CaptionSegment { startMs: number; text: string }
export interface YouTubeTranscript {
	id: string; url: string; title: string; channel: string; language: string;
	autoGenerated: boolean; durationSeconds: number; segments: CaptionSegment[];
}

export function youtubeVideoId(input: string): string {
	let url: URL;
	try { url = new URL(input); } catch { throw new Error("Provide a YouTube video URL."); }
	if (url.protocol !== "https:") throw new Error("Use an HTTPS YouTube video URL.");
	const host = url.hostname.toLowerCase();
	let id: string | null = null;
	if (host === "youtu.be") id = url.pathname.split("/")[1] || null;
	else if (["youtube.com", "www.youtube.com", "m.youtube.com", "music.youtube.com"].includes(host)) {
		id = url.pathname === "/watch" ? url.searchParams.get("v") :
			/^\/(?:shorts|live|embed)\//.test(url.pathname) ? url.pathname.split("/")[2] || null : null;
	}
	if (!id || !VIDEO_ID.test(id)) throw new Error("This is not a supported YouTube video URL.");
	return id;
}

function decodeXml(value: string): string {
	return value.replace(/&(#x[0-9a-f]+|#[0-9]+|amp|lt|gt|quot|apos|nbsp);/gi, (_match, entity: string) => {
		switch (entity.toLowerCase()) {
			case "amp": return "&"; case "lt": return "<"; case "gt": return ">";
			case "quot": return '"'; case "apos": return "'"; case "nbsp": return " ";
		}
		const code = entity.toLowerCase().startsWith("#x") ? parseInt(entity.slice(2), 16) : parseInt(entity.slice(1), 10);
		return Number.isFinite(code) && code <= 0x10ffff ? String.fromCodePoint(code) : "";
	});
}

function cleanCaption(value: string): string {
	return decodeXml(value.replace(/<[^>]*>/g, "")).replace(/\s+/g, " ").trim();
}

export function parseCaptions(body: string): CaptionSegment[] {
	if (body.length > 2_000_000) throw new Error("Caption track is too large to inspect safely.");
	if (body.trimStart().startsWith("{")) {
		try {
			const data = JSON.parse(body) as { events?: Array<{ tStartMs?: number; segs?: Array<{ utf8?: string }> }> };
			return (data.events || []).flatMap((event) => {
				const text = cleanCaption((event.segs || []).map((segment) => segment.utf8 || "").join(""));
				return text ? [{ startMs: event.tStartMs || 0, text }] : [];
			});
		} catch { throw new Error("Could not parse YouTube captions."); }
	}
	const segments: CaptionSegment[] = [];
	for (const match of body.matchAll(/<p\b([^>]*)>([\s\S]*?)<\/p>/g)) {
		const start = /\bt="(\d+)"/.exec(match[1]);
		const text = cleanCaption(match[2]);
		if (start && text) segments.push({ startMs: Number(start[1]), text });
	}
	if (segments.length) return segments;
	for (const match of body.matchAll(/<text\b([^>]*)>([\s\S]*?)<\/text>/g)) {
		const start = /\bstart="([\d.]+)"/.exec(match[1]);
		const text = cleanCaption(match[2]);
		if (start && text) segments.push({ startMs: Math.round(Number(start[1]) * 1000), text });
	}
	return segments;
}

function captionTrackUrl(value: unknown): string {
	if (typeof value !== "string") throw new Error("YouTube did not provide a caption URL.");
	let url: URL;
	try { url = new URL(value); } catch { throw new Error("YouTube provided an invalid caption URL."); }
	if (url.protocol !== "https:" || !["youtube.com", "www.youtube.com"].includes(url.hostname) || url.pathname !== "/api/timedtext") {
		throw new Error("YouTube provided an unexpected caption URL.");
	}
	return url.href;
}

export async function fetchYouTubeTranscript(input: string, language?: string, fetcher: typeof fetch = fetch): Promise<YouTubeTranscript> {
	const id = youtubeVideoId(input);
	const response = await fetcher(PLAYER_URL, {
		method: "POST", headers: { "Content-Type": "application/json", "User-Agent": `com.google.android.youtube/${CLIENT_VERSION} (Linux; U; Android 14)` },
		body: JSON.stringify({ context: { client: { clientName: "ANDROID", clientVersion: CLIENT_VERSION, hl: "en", gl: "US" } }, videoId: id }),
		signal: AbortSignal.timeout(12_000), redirect: "error",
	});
	if (!response.ok) throw new Error(`YouTube player request failed (${response.status}).`);
	const player = await response.json() as any;
	if (player.playabilityStatus?.status !== "OK") throw new Error(player.playabilityStatus?.reason || "Video is unavailable.");
	const tracks = player.captions?.playerCaptionsTracklistRenderer?.captionTracks;
	if (!Array.isArray(tracks) || !tracks.length) throw new Error("This video has no accessible captions.");
	const requested = language?.trim().toLowerCase();
	const choices = requested ? tracks.filter((track: any) => track.languageCode?.toLowerCase() === requested) : tracks;
	if (!choices.length) throw new Error(`No ${requested} captions are available. Available: ${tracks.map((track: any) => track.languageCode).join(", ")}.`);
	const defaultIndex = player.captions?.playerCaptionsTracklistRenderer?.audioTracks?.[0]?.defaultCaptionTrackIndex;
	const track = (!requested && Number.isInteger(defaultIndex) ? tracks[defaultIndex] : undefined) ||
		choices.find((item: any) => item.languageCode === "en" && item.kind !== "asr") ||
		choices.find((item: any) => item.languageCode === "en") ||
		choices.find((item: any) => item.kind !== "asr") || choices[0];
	const captions = await fetcher(captionTrackUrl(track.baseUrl), { signal: AbortSignal.timeout(12_000), redirect: "error" });
	if (!captions.ok) throw new Error(`Caption request failed (${captions.status}).`);
	const body = await captions.text();
	if (!body.trim()) throw new Error("YouTube returned an empty caption track.");
	const segments = parseCaptions(body);
	if (!segments.length) throw new Error("Could not read usable captions from this video.");
	return {
		id, url: `https://www.youtube.com/watch?v=${id}`,
		title: String(player.videoDetails?.title || "Untitled video"),
		channel: String(player.videoDetails?.author || "Unknown channel"),
		language: String(track.languageCode || "unknown"), autoGenerated: track.kind === "asr",
		durationSeconds: Number(player.videoDetails?.lengthSeconds) || Math.ceil(segments.at(-1)!.startMs / 1000), segments,
	};
}

export function transcriptParts(segments: CaptionSegment[], maxCharacters = 10_000): CaptionSegment[][] {
	const parts: CaptionSegment[][] = [];
	let current: CaptionSegment[] = [];
	let length = 0;
	for (const segment of segments) {
		const size = segment.text.length + 18;
		if (current.length && length + size > maxCharacters) { parts.push(current); current = []; length = 0; }
		current.push(segment); length += size;
	}
	if (current.length) parts.push(current);
	return parts;
}

export function captionTime(startMs: number): string {
	const seconds = Math.floor(startMs / 1000);
	return `${Math.floor(seconds / 3600).toString().padStart(2, "0")}:${Math.floor((seconds % 3600) / 60).toString().padStart(2, "0")}:${(seconds % 60).toString().padStart(2, "0")}`;
}
