import { captionTime, fetchYouTubeTranscript, parseCaptions, transcriptParts, youtubeVideoId } from "../.pi/core/youtube-transcript.ts";
import vaultGarage from "../.pi/extensions/vault-garage.ts";

let failures = 0;
function assert(condition: unknown, message: string) {
	if (condition) console.log(`PASS: ${message}`);
	else { failures++; console.error(`FAIL: ${message}`); }
}

assert(youtubeVideoId("https://youtu.be/kzcI5F4tGiU") === "kzcI5F4tGiU", "short YouTube URL is accepted");
assert(youtubeVideoId("https://www.youtube.com/shorts/kzcI5F4tGiU") === "kzcI5F4tGiU", "YouTube Shorts URL is accepted");
for (const url of ["https://notyoutube.com/watch?v=kzcI5F4tGiU", "http://www.youtube.com/watch?v=kzcI5F4tGiU", "https://www.youtube.com/watch?v=bad"]) {
	let rejected = false;
	try { youtubeVideoId(url); } catch { rejected = true; }
	assert(rejected, `invalid video URL is rejected: ${url}`);
}

const xml = '<timedtext><body><p t="0" d="1000"><s>Hello</s><s> &amp; welcome</s></p><p t="1500" d="1000"><s>Next idea</s></p></body></timedtext>';
const parsed = parseCaptions(xml);
assert(parsed.length === 2 && parsed[0].text === "Hello & welcome" && parsed[1].startMs === 1500, "timed XML captions retain text and timestamps");
assert(parseCaptions('{"events":[{"tStartMs":2500,"segs":[{"utf8":"One "},{"utf8":"idea"}]}]}')[0].text === "One idea", "JSON captions are supported");
assert(parseCaptions('<transcript><text start="2.5" dur="1">Legacy &lt;text&gt;</text></transcript>')[0].text === "Legacy <text>", "legacy caption XML is supported");
assert(captionTime(3_661_000) === "01:01:01" && transcriptParts(parsed, 35).length === 2, "transcript is split into timestamped bounded parts");

const player = {
	playabilityStatus: { status: "OK" }, videoDetails: { title: "Test video", author: "Test channel", lengthSeconds: "12" },
	captions: { playerCaptionsTracklistRenderer: { captionTracks: [
		{ languageCode: "en", kind: "asr", baseUrl: "https://www.youtube.com/api/timedtext?v=kzcI5F4tGiU" },
	] } },
};
const calls: string[] = [];
const mockFetch = (async (input: RequestInfo | URL) => {
	const url = String(input);
	calls.push(url);
	return new Response(url.includes("/youtubei/") ? JSON.stringify(player) : xml, { status: 200 });
}) as typeof fetch;
const transcript = await fetchYouTubeTranscript("https://www.youtube.com/watch?v=kzcI5F4tGiU", "en", mockFetch);
assert(calls.length === 2 && transcript.title === "Test video" && transcript.autoGenerated && transcript.segments.length === 2, "caption reader uses only player and caption requests");
const multilingualPlayer = structuredClone(player);
multilingualPlayer.captions.playerCaptionsTracklistRenderer.captionTracks.push({ languageCode: "es", kind: "asr", baseUrl: "https://www.youtube.com/api/timedtext?v=kzcI5F4tGiU&lang=es" });
(multilingualPlayer.captions.playerCaptionsTracklistRenderer as any).audioTracks = [{ defaultCaptionTrackIndex: 1 }];
const originalLanguage = await fetchYouTubeTranscript("https://youtu.be/kzcI5F4tGiU", undefined, (async (input: RequestInfo | URL) =>
	new Response(String(input).includes("/youtubei/") ? JSON.stringify(multilingualPlayer) : xml, { status: 200 })) as typeof fetch);
assert(originalLanguage.language === "es", "default caption follows the video's audio track when available");

let missingCaptions = false;
try {
	await fetchYouTubeTranscript("https://youtu.be/kzcI5F4tGiU", "en", (async () => new Response(JSON.stringify({ playabilityStatus: { status: "OK" } }), { status: 200 })) as typeof fetch);
} catch (error) { missingCaptions = (error as Error).message.includes("no accessible captions"); }
assert(missingCaptions, "video without captions fails clearly");

let blockedCaptionHost = false;
try {
	const unsafePlayer = structuredClone(player);
	unsafePlayer.captions.playerCaptionsTracklistRenderer.captionTracks[0].baseUrl = "https://example.com/private";
	await fetchYouTubeTranscript("https://youtu.be/kzcI5F4tGiU", "en", (async () => new Response(JSON.stringify(unsafePlayer), { status: 200 })) as typeof fetch);
} catch (error) { blockedCaptionHost = (error as Error).message.includes("unexpected caption URL"); }
assert(blockedCaptionHost, "caption URL cannot redirect the tool to another host");

const tools = new Map<string, any>();
vaultGarage({ registerTool: (tool: any) => tools.set(tool.name, tool), registerCommand: () => {} } as any);
assert(tools.has("read_youtube_transcript") && tools.has("capture_learning_source"), "Pi exposes transcript reading and grounded summary capture");
const invalid = await tools.get("read_youtube_transcript").execute("invalid", { url: "https://example.com/watch?v=kzcI5F4tGiU" });
assert(invalid.isError && invalid.content[0].text.includes("not a supported YouTube"), "transcript tool rejects unsupported URLs without a request");

if (process.argv.includes("--live")) {
	const live = await fetchYouTubeTranscript("https://www.youtube.com/watch?v=kzcI5F4tGiU", "en");
	assert(live.segments.length > 100 && live.title === "How I Use AI to Learn Things", "live public YouTube captions are readable");
}

if (failures) process.exit(1);
console.log("YouTube transcript tests passed.");
